FS:
  1:
    - [1, -1]
  2:
    - [1, -1]
  sex: false
  degree: 1st
  path: true

PO:
  1:
    - [1,]
  sex: false
  degree: 1st
  path: true

GPAV:
  sex: false
  degree: 2nd
  

PHS:
  1:
    - [1, -1]
  sex: true
  degree: 2nd
  parent: HS
  path: true

MHS:
  2: 
    - [1, -1]
  sex: true
  degree: 2nd
  parent: HS
  path: true

HS:
  1:
    - [1, -1]
  sex: false
  degree: 2nd
  path: true

AV:
  1:
    - [1, 1, -1]
    - [1, 1, -1]
  sex: false
  degree: 2nd
  parent: GPAV
  path: true

HAV:
  1:
    - [1, 1, -1]
  sex: false
  degree: 3rd
  path: true

GP:
  1:
    - [1, 1]
  sex: false
  degree: 2nd
  parent: GPAV
  path: true

PGP:
  1:
    - [1, 1]
  sex: true
  degree: 2nd
  parent: GP
  path: true

MGP:
  2:
    - [1, 1]
  sex: true
  degree: 2nd
  parent: GP
  path: true

GGP:
  1:
    - [1, 1, 1]
  sex: false
  degree: 3rd
  path: true

DCO:
  1:
    - [1, 1, -1, -1]
    - [1, 1, -1, -1]
  2:
    - [1, 1, -1, -1]
    - [1, 1, -1, -1]
  sex: false
  degree: 3rd+
  path: true

HSCO:
  1:
    - [1, -1]
  2:
    - [1, 1, -1, -1]
    - [1, 1, -1, -1]
  sex: false
  degree: 2nd+
  path: true

HSHCO:
  1:
    - [1, -1]
  2:
    - [1, 1, -1, -1]
  sex: false
  degree: 2nd+
  path: true

CO:
  1:
    - [1, 1, -1, -1]
    - [1, 1, -1, -1]
  sex: false
  degree: 3rd
  path: true

HCO:
  1:
    - [1, 1, -1, -1]
  sex: false
  degree: 4th
  path: true

DHCO:
  1:
    - [1, 1, -1, -1]
  2:
    - [1, 1, -1, -1]
  sex: false
  degree: 4th+
  path: true

DHAV:
  1:
    - [1, 1, -1]
  2:
    - [1, 1, -1]
  sex: false
  degree: 3rd+
  path: true

COHCO:
  1:
    - [1, 1, -1, -1]
    - [1, 1, -1, -1]
  2:
    - [1, 1, -1, -1]
  sex: false
  degree: 3rd+
  path: true
